config/routes.rb
SerenaVaccari::Application.routes.draw do


  devise_for :users

  devise_scope :user do
    get '/serry', to: "devise/sessions#new"
  end

  root to: "projects#index"

  resources :projects do
    get 'carousel', on: :member
    resources :photos
  end

  get ':action', to: 'pages#action'

end

app/models/options/base.rb
module Options
  class Base
    class << self
      attr_accessor :options

      def all
        @options
      end

      def all_as_sym
        @options.map(&:to_sym)
      end

      # Converts it to an array of arrays
      # [0]
      #   [0] 'tradesperson_assistant'
      #   [1] 'Tradesperson's Assistant'
      #
      def all_as_select
        @options.map { |x| [self.new(x).try(:to_s), x] }
      end
    end
  end
end

app/models/options/categories.rb
module Options
  class Categories < Base
    @options = ['residential', 'commercial', 'landscape', 'experimental']

    def initialize(option)
      @option = option
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {
                      :medium => "500x500>",
                      :thumb => "150x150>"
                    },
                    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :project

  default_scope { order(position: :asc) }

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :cover,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  default_scope { order(position: :asc) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  # before_filter :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index,:contact,:about]

  def contact
  end

  def about
    @sidemenu = { aboutme: "about me",
                  passioni: "whatever passion",
                  curriculum: "curriculum",
                  collaborations: "collaborations"}
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_project
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :delete_image, only: [:destroy]

  def edit
  end


  def create
    @photo = @project.photos.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @project, notice: 'Photo successfully uploaded.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @photo.update(photo_params)
    redirect_to @project, notice: 'Photo successfully updated.'
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_project
      @project = Project.find_by_id params[:project_id]
    end

    def set_photo
      @photo = Photo.find_by_id params[:id]
    end

    def delete_image
      @photo.image = nil
      @photo.save
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :description, :position, :image, :project_id)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :delete_cover, only: [:destroy]
  before_action :set_side_menu

  respond_to :html, :json

  def index
    @projects = Project.all
  end

  def show
    @photo = Photo.new
    @photos = @project.photos.order('position asc')

    @photos_json = Jbuilder.encode do |json|
      json.array! @photos do |photo|
        json.name photo.name
        json.description photo.description
        json.position photo.position
        json.url photo.image.url
        json.updated_at photo.image_updated_at
      end
    end
    respond_to do |format|
      format.html
      format.json { render json: @photos_json }
    end
  end

  def carousel
    @project = Project.find params[:id]
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.

  def set_project
    @project = Project.find_by_id params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :category, :position, :location, :year, :note, :cover, photos_attributes: [ :id, :name, :description, :image, :project_id, :_destroy] )
  end

  def delete_cover
    @project.cover = nil
    @project.save
  end

  def set_side_menu
    @sidemenu = { works: "works",
                  competitions: "competitions",
                  workshops: "workshops",
                  studies: "studies"}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.slim
.footer
  .container
    .pull-right
      | All Rights Reseverd &copy; 2016

app/views/layouts/_header.html.slim
nav.navbar role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"
        h1 arch. serena vaccari
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-justify.header-list.fancy-list
        li
          a.black-link href="/projects"
            | projects
        li
          a.black-link href="/about"
            | about me
        li
          a.black-link href="/contact"
            | contact
        - if current_user
          li = link_to "Log out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Arch. Serena Vaccari
    meta name="description" content="Serena Vaccari. Architect. Personal Website."
    meta name="vewport" content="width=device-width,initial-scale=1"
    meta name="google-site-verification" content=ENV['GOOGLE_VERIFICATION']
    = favicon_link_tag 'icon.ico'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", media: 'all'
    link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet" type="text/css"
    = csrf_meta_tags
  body  class=params[:controller].split("/").try(:join, " ") class=params[:action]
    .vertical-line
    = render 'layouts/header'
    - if notice
      .alert.alert-success.alert-dismissable
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          i.fa.fa-times-circle
        = notice
    - if alert
      .alert.alert-danger.alert-dismissable
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          i.fa.fa-times-circle
        = alert
    .main-container
      = yield
    = render 'layouts/footer'

    #carousel-container


coffee:
  $ ->
    affixFooter = ->
      windowHeight = window.innerHeight
      footerHeight = $('.footer').outerHeight(true)
      navHeight = $('nav').outerHeight(true)

      minMainHeight = windowHeight - footerHeight - navHeight

      $('.main-container').css('min-height', "#{minMainHeight}px")

    $(window).resize ->
      affixFooter()

    affixFooter()

javascript:
  // Google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72509655-1', 'auto');
  ga('send', 'pageview');

app/views/pages/_history.html.slim
.history
  .history-line
    .years
      | 2015
    .description
      | Project Architect at&nbsp;
      b
        = link_to "Danny Broe Architect", 'http://www.houzz.com.au/pro/dannybroearchitect/danny-broe-architect', target: '_blank'
      |  | Sydney, Australia

  .history-line
    .years
      | 2014
    .description
      | Moved to Sydney and started to work at&nbsp;
      b
        = link_to "Danny Broe Architect", 'http://www.dannybroearchitect.com', target: '_blank'
    .description.inverted
      | Volunteer at Architecture for Humanity | Sydney, Australia

  .history-line.double
    .years
      | 2013
    .description.inverted
      | Collaboration with Architect Giorgio Ciarallo
      |  | Milan, Italy
    .description.inverted
      | Volunteer at&nbsp;
      b
        = link_to "Instituto Çarakura - Permaculture centre", 'http://www.institutocarakura.org.br', target: '_blank'
      |  | Florianopolis - Brazil
    .description
      | Junior designer at&nbsp;
      b
        = link_to "McFIT Italia", 'http://www.mcfit.com', target: '_blank'
      |  |  Milan, Italy


  .history-line.triple
    .years
      | 2012
    .description
      | Registered Architect
    .description.inverted
      b
        = link_to "Workshop", 'http://www.archilovers.com/projects/61186/abitare-minimo-maga-gallarate.html', target: '_blank'
      |&nbsp;for the construction of a minimal house in wood with Architects Rintala & Eggertsson, Paolo Mestriner e Massimiliano Spadoni
      |  |  MAGA, Gallarate Art Museum
    .description.inverted
      | Collaboration with&nbsp;
      b
        = link_to "Tim Power Architects", 'http://www.tim-power.com/', target: '_blank'
      |  |  Milan, Italy
    .description
      | Landscape architect at&nbsp;
      b
        = link_to "TH Treibhaus + Lavaland", 'http://www.lavaland.biz/', target: '_blank'
      | &nbsp;| Berlin, Germany

    .description.inverted
      | Co-operation with&nbsp;
      b
        = link_to "Barreca & La Varra", 'http://www.barrecaelavarra.it', target: '_blank'
      |  and&nbsp;
      b
        = link_to "Connecting Cultures", 'http://www.connectingcultures.info', target: '_blank'
      |  |  Milan, Italy



  .history-line
    .years
      | 2011
    .description
      | Master Degree in Architecture at Politecnico di Milano | final mark: 110/110


  .history-line.triple
    .years
      | 2010
    .description
      | Intern at&nbsp;
      b
        = link_to "Bruno Fioretti Marquez Architekten", 'http://www.bfm-architekten.de', target: '_blank'
      | &nbsp;| Berlin, Germany
      p 1st prize in the competition for the Houses of the Bauhaus Masters in Dessau, Germany
      p 1st prize in the competition for new kindergarden in the university campus of Karlsruhe, Germany

    .description.inverted
      | 1st prize in the competition Architektursommer Rügen 2010 and Construction workshop with prof. Arch. Regine Leibinger

    .description
      | One semester at Technische Universität Berlin | Berlin, Germany


  .history-line
    .years
      | 2009
    .description.inverted
      | participation at WAAS - Workshop Advanced Architectural Structures at Technische Universiteit Eindhoven | Eindhoven, Netherlands


  .history-line.double
    .years
      | 2008
    .description
      | Bachelor Degree in “Scienze dell’Architettura” at Politecnico di Milano

    .description.inverted
      | Intern at&nbsp;
      b
        = link_to "Capinha Lopes e Associados", 'http://www.capinha-lopes.pt', target: '_blank'
      | &nbsp;| Lisbon, Portugal

    .description
      | One academic year at Universidade Lusiada | Lisbon, Portugal


  .history-line
    .years
      | 2007
    .description.inverted
      | Organizer of european cultural exchanges and architecture, design, engineer courses with the association “Best Milano” | Milan, Italy

  .history-line
    .years
      | 2006
    .description.inverted
      | Sustainable design course at “Instituto Superior Técnico” | Lisbon, Portugal

  .history-line
    .years
      | 2005
    .description.inverted
      | Attended one year of “Indrustrial Design” at Politecnico di Milano - campus Bovisa | Milan, Italy

app/views/pages/about.html.slim
.container-fluid.main-body.col-md-8.col-md-offset-2
  h1 about me
  .about-container
    #aboutme.section style='margin-left:110px;'

      p Originally from Milan, Serena studied Architecture at Technische Universität in Berlin, Universidade Lusiada in Lisbon and Politecnico di Milano, where she completed her Bachelor and Masters of Architecture in 2011 with first class honours. Since 2012 Serena is a registered architect in Milan.

      p Before moving to Sydney, she worked with different firms in Germany, Portugal and Italy, including BFM Architekten and Capinha Lopes.

      p She is a keen traveller and she can communicate in up to 5 languages.
      | Her interests include design, landscape architecture and urban design and she has been actively engaged in many architecture competitions.


      p She is passionate about humanitarian architecture, she volunteered in a permaculture center in Brasil and she participates in various workshops of experimental construction.

  .skill-container
    .row.skill-row
      .col-xs-1.col-xs-offset-1
        .skills Archicad
      .col-xs-1.col-xs-offset-1
        .skills Autocad
      .col-xs-1.col-xs-offset-1
        .skills
          .lines3 Adobe Creative Suite
      .col-xs-1.col-xs-offset-1
        .skills Sketchup
      .col-xs-1.col-xs-offset-1
        .skills Revit
      .col-xs-1.col-xs-offset-1
        .skills
          .lines2 Vector works

    .row.skill-row
      .col-xs-1.col-xs-offset-2
        .skills Italiano
      .col-xs-1.col-xs-offset-1
        .skills English
      .col-xs-1.col-xs-offset-1
        .skills Deutsch
      .col-xs-1.col-xs-offset-1
        .skills Português
      .col-xs-1.col-xs-offset-1
        .skills Español



  .about-container
    = render partial: 'history'

.clearfix


coffee:
  $ ->
    resizeImage = ->
      height = $('body').css('height')

      year = $('.years')[0]
      yearLeft = year.getBoundingClientRect().left
      imageLeft = yearLeft + $(year).width()/2

      $('.vertical-line').css('height', height)
      $('.vertical-line').css('left', "#{imageLeft}px")

    $(window).resize ->
      resizeImage()

    resizeImage()

app/views/pages/contact.html.slim
.container-fluid.main-body.col-md-12.col-lg-4.col-lg-offset-4
  br
  br
  br
  br
  br
  br


  .row.contacts-box
    .col-xs-5
      .row
        | EMAIL
      .row
        | PORTFOLIO 16
      .row
        | PORTFOLIO 13
      .row
        | CURRICULUM VITAE
      .row
        | LINKEDIN

    .col-xs-7
      .row
        | |
        =< mail_to 'sere.vaccari@gmail.com', 'sere.vaccari@gmail.com', class: 'black-link'
      .row
        | |
        =< link_to "projects", "http://www.serenavaccari.com/portfolio_serena.pdf", class: 'black-link', target: "_blank"
      .row
        | |
        =< link_to "issuu.com/serena.vaccari", "http://issuu.com/serena.vaccari/docs/portfolio_2011", class: 'black-link', target: "_blank"
      .row
        | |
        =< link_to "Serena Vaccari", "http://www.serenavaccari.com/curriculum_serena.pdf", class: 'black-link', target: "_blank"
      .row
        | |
        =< link_to "https://it.linkedin.com/in/serena-vaccari-78bbab45/en", class: 'black-link', target: '_blank' do
          .fa.fa-linkedin-square

.clearfix

app/views/projects/_carousel.html.slim
- if project.photos.any?
  #myModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
    .modal-dialog role="document"
      .modal-content
        #carousel.carousel.slide data-ride="carousel"

          .carousel-inner role="listbox"
            - project.photos.each_with_index do |photo, index|
              .item class="#{'active' if index == 0}"
                = image_tag photo.image.url, alt: photo.name
                - if photo.name.present?
                  .carousel-caption
                    p = photo.name

          a.left.control.left data-slide="prev" href="#carousel" role="button"
            span.fa.fa-angle-left aria-hidden="true"
            span.sr-only Previous
          a.right.control.right data-slide="next" href="#carousel" role="button"
            span.fa.fa-angle-right aria-hidden="true"
            span.sr-only Next
    .label
      h3 = project.name
      - if project.description.present?
        p = project.description
      p
        => project.location
        | |
        =< project.year

coffee:
  $ ->
    $('#myModal').modal('show')
    $('#carousel').bcSwipe({ threshold: 50 })

app/views/projects/_form.html.slim
= simple_nested_form_for(@project, html: {:role => 'form', :class => 'form'}) do |f|
  .form-group
    = f.text_field :name, placeholder: 'name', :class => 'form-control'
  .form-group
    = f.text_area :description, placeholder: 'description', :class => 'form-control'
  .form-group
    = f.number_field :position, placeholder: 'position',  class: 'form-control'
  .form-group
    = f.select(:category, Options::Categories.all_as_sym, {}, {:class => 'form-control'})
  .form-group
    = f.text_field :location, placeholder: 'location', :class => 'form-control'
  .form-group
    = f.number_field :year, placeholder: 'year', :class => 'form-control'
  .form-group
    = f.text_field :note, placeholder: 'note', :class => 'form-control'
  .form-group
    = f.label 'Add a cover image for this project ( jpg only )'
    = f.file_field :cover, placeholder: 'cover image' , :class => 'form-control'

    h3 photos
    #photos
      = f.fields_for :photos do |builder|
        .row.resource-row.panel.panel-default
          .panel-body
            .col-md-8
              .row
                .col-md-6
                  .form-group
                    = builder.input :name, input_html: {class: 'form-control'}, label: false, placeholder: 'Name'
                .col-md-6
                  .form-group
                    = builder.input :position, input_html: {class: 'form-control'}, label: false, placeholder: 'Position'
              .row
                .col-md-12
                  .form-group
                    = builder.input :description, input_html: {class: 'form-control'}, label: false, placeholder: 'Description'
            .col-md-3
              - if !builder.object.image.present?
                = builder.input :image, as: :file
              - else
                br
                - if builder.object.image.exists?
                  = image_tag builder.object.image.url(:thumb)
                - else
                  | The file is missing
            .col-md-1
              .form-group
                br
                = builder.link_to_remove "X"
    .row
      .col-md-4
        = f.link_to_add "Add a Photo", :photos, :data => { :target => "#photos" }



  .center
    .form-group
      = f.submit :class => "btn btn-success "

app/views/projects/_secondary_menu.html.slim
ul.secondary-menu.fancy-list
  - Options::Categories.all_as_sym.each do |cat|
    .black-link data-category="#{cat}"
      li
        = cat

app/views/projects/carousel.js.erb
$('#carousel-container').html("<%= escape_javascript render(partial: 'carousel', locals: { project: @project }) %>");

app/views/projects/edit.html.slim
.container
  h1 edit project

  = render 'form'

  = link_to 'Back', project_path

app/views/projects/index.html.slim
.container-fluid.main-body.col-md-8.col-md-offset-2.col-xs-12
  = render 'secondary_menu'
  br
  .clearfix
  - if current_user
    .row.new-project
      = link_to 'new project', new_project_path
    br

  .project-container
    .row.col-md-12
      - @projects.map do |project|
        .col-md-4.col-xs-12.project-div id="#{project.id}" class="#{project.category}"
          - if project.photos.any?
            = link_to carousel_project_path(project), remote: true do
              = image_tag project.cover.url, class: 'project'
          - else
            = image_tag project.cover.url, class: 'project'
          p = project.name
          - if current_user
            = link_to 'modify', project_path(project)
.clearfix


coffee:
  $ ->
    visualizeCategory = (category) ->
      $('.project-container .project-div').hide()
      $('.project-container .project-div.' + category).show()

    $('.secondary-menu').on 'click', '.black-link', ->
      visualizeCategory $(this).data('category')

app/views/projects/new.html.erb
<h1>add a new project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

    

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class='container project-show'>
  <div class="row">
    <div class="col-md-3 cover">
      <p><%= image_tag @project.cover.url(:thumb) %></p>
    </div>

    <div class="col-md-3">
      <h3><%= @project.name %></h3>
      <p><%= @project.category %></p>
      <p><%= @project.description %></p>
      <p><%= @project.location %></p>
      <p><%= @project.year %></p>
      <p><%= @project.note %></p>
      <%= link_to 'edit', edit_project_path(@project) %> |
      <%= link_to 'delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>

    <div class="col-md-4">
      <h4>Add a new photo</h4>
      <%= form_for([@project, @photo], html: {:role => 'form', class: 'form'}) do |f| %>

      <div class="form-group">
        <%= f.text_field :name, placeholder: 'name', :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.text_area :description, placeholder: 'description', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.number_field :position, placeholder: 'position',  class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.file_field :image, :class => 'form-control'  %>
      </div>

      <div class="form-group">
        <%= f.submit 'Send photo', :class => "btn btn-success " %>
      </div>

      <% end %>
    </div>

  </div>

  <div class="row">
    <div class="photos-list">

    </div>
  </div>

  <div class="row ">
    <% @photos.each do |photo| %>
        <div class="photo">
        <%= image_tag photo.image.url(:thumb)   %>
        <h5><%= photo.name %></h5>
        <p><%= photo.description %></p>

        <div>
          <%= form_for([@project, photo], html: {:role => 'form', id:"edit_#{photo.id}",class: 'form edit-photo'}) do |f| %>
            <%= f.text_field :name, placeholder: 'name', :class => 'form-control' %>
            <%= f.text_area :description, placeholder: 'description', class: 'form-control' %>
            <%= f.number_field :position, placeholder: 'position', class: 'form-control' %>
            <%= f.file_field :image, :class => 'form-control'  %>
            <%= link_to 'close', "#", :class => "btn btn-worning close-form" %>
            <%= f.submit 'save changes', :class => "btn btn-success " %>
          <% end %>
        </div>
        <%= link_to 'edit', "##{photo.id}", id:"photo_#{photo.id}",class: "show-photo-edit" %>  |
        <%= link_to 'delete', project_photo_path(@project, photo), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
</div>
<div id="token" style="display: none;"><%= form_authenticity_token %></div>

<script>

  $('.edit-photo').hide();
  $('.show-photo-edit').on("click",function() {
    repl = /(^photo_)/
    edit = '#edit_' + this.id.replace(repl,"")
    $(edit).toggle();
  });

</script>